### ISSUE TITLE
Error when 2 elements are too close together

### ISSUE THREAD

**Issue by Max-Verbinnen** [stanko-arbutina/arrow-line#11]
I'm using your awesome library for a chess game, but when I draw an arrow between two squares that are right next to each other I get the following error:

![screenshot](https://user-images.githubusercontent.com/64088654/113745774-e3f44800-9705-11eb-9a2b-401c7af99b9e.png)

There's still an arrow but you can only see a skewed endpoint as shown by the red rectangle. Is there a way to fix this?
Thanks!

**Comment by stanko-arbutina** [comment]
Hey, I glad you like it! 
I've experimented with putting the elements very close together, but I wasn't able to replicate the error you are getting.
It seems that there is some kind of bug in pivot calculation for some combination of parameters.. could you provide a code example?

**Comment by Max-Verbinnen** [comment]
Thanks for your response!
These are the parameters I'm using: 
```javascript
const arrow = arrowLine(`.${start}`, `.${end}`, {
    curvature: Math.pow(10, -9),
    color: "#769656",
    thickness: 1.5
});
```
I need straight lines in my game, so I had to use a workaround for the non-zero curvature value. This seems a bit weird, however you get the same error when setting the curvature to 1.5 or 2 for example.
Thanks!

**Comment by stanko-arbutina** [comment]
Thank you for clearing this up - I've managed to reproduce the error (on Chrome, but not on Firefox) - there was indeed a bug when calculating pivots. I've published a new version in which this should be fixed.
Good point about the zero curvature - I've added support for straight lines (just set the curvature to 0), thanks for pointing that out!

Let me know if you're still having issues.
